import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Cart",
  description: "Generated by Next.js",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
