import Container from "@/shared/components/shared/container";
import Header from "@/shared/components/shared/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Cart",
  description: "Generated by Next.js",
};

interface Props {
  children: React.ReactNode;
}

export default function CheckoutLayout({ children }: Props) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header hasSearch={false} hasCart={false} className="border-gray-200" />
        {children}
      </Container>
    </main>
  );
}
